import = [
    "~/.config/alacritty/themes/monokai_charcoal.toml"
]

[cursor]
style = "Block"

[font]
size = 12.0

[font.normal]
family = "Gintronic"
style = "Regular"

[font.bold]
family = "Gintronic"
style = "Bold"

[font.italic]
family = "Gintronic"
style = "Italic"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

[window]
dimensions = { columns = 90, lines = 40 }
padding = { x = 10, y = 10 }
