import = [
    "~/.config/alacritty/themes/aura.toml"
]

[cursor]
style = "Block"

[font]
size = 11.0

[font.normal]
family = "Monoid Nerd Font"
style = "Retina"

[font.bold]
family = "Monoid Nerd Font"
style = "Bold"

[font.italic]
family = "Monoid Nerd Font"
style = "Italic"

[terminal]
osc52 = "CopyPaste"

[mouse]
hide_when_typing = true

